spring:
    application:
        name: stockmanager-brokerage
    jackson.serialization:
        indent_output: true
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        url: jdbc:postgresql://wsl.local:5432/brokerage
        username: brokerage
        password: brokerage
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 8081
eureka:
    client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka
keycloak:
    realm: stockmanager
    auth-server-url: http://wsl.local:8083/auth
    ssl-required: external
    resource: stockmanager-backend
    use-resource-role-mappings: true
    bearer-only: true
logging:
    level:
        root: INFO
        org.springframework: INFO
        br.com.mb: DEBUG
    logstash:
        enabled: true
        url: wsl.local:5000
        #trustStoreLocation: /tmp/location/sample.jks
        #trustStorePassword: 123456
        ignorePatterns: /(actuator|swagger|webjars).*
        logHeaders: true