spring:
    application:
        name: stockmanager-brokerage
    jackson.serialization:
        indent_output: true
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        url: jdbc:postgresql://wsl.local:5432/brokerage
        username: brokerage
        password: brokerage
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 8081
eureka:
    client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework: INFO